Add proper quote posts to Pleroma
h3poteto/megalodon pull request #1706
Opened 2023-05-07 02:36 UTC by CPlusPatch

This pull request adds the ability to see quote posts on Pleroma and Akkoma by properly using the `quote` field returned by the Pleroma API. All tests have passed.

It will also be possible to easily add support for Mastodon and Misskey quotes with a few more lines of code

2023-05-21 14:35 UTC, h3poteto commented
Sorry for the late response. Since this is a breaking change for entities, it will be included in the next minor release. Please wait a little more.

2023-05-21 14:36 UTC, h3poteto approved these changes
I will merge this in the next minor release.

2023-05-31 15:55 UTC, h3poteto commented
@CPlusPatch Hi, I have a question about Pleroma. Now does Pleroma support quote? I can't find any documents about quote in https://docs-develop.pleroma.social/
And my Pleroma instance does not return `quote` field in the timeline.

2023-05-31 19:15 UTC, CPlusPatch commented
I'm using Akkoma which is a very popular Pleroma fork, but it should work in latest Pleroma too, here are some screenshots:

![image](https://github.com/h3poteto/megalodon/assets/42910258/56d28ce6-88a8-459b-ba95-2f27b98fbf90)

![image](https://github.com/h3poteto/megalodon/assets/42910258/35a3c737-510d-42f8-96e2-51e8b1adf3a5)

2023-05-31 19:18 UTC, CPlusPatch commented
Besides, quoting also works on Misskey and its derivatives:
![image](https://github.com/h3poteto/megalodon/assets/42910258/65a7291d-bb7f-4833-bbc7-22c0aa6d1b56)

Mastodon is also planning to add support for it soon!

2023-06-01 00:28 UTC, h3poteto commented
At the moment, Pleroma does not support quote.
![Screenshot from 2023-06-01-09-25-17](https://github.com/h3poteto/megalodon/assets/4631959/565bd991-5d6b-4cc1-b1fe-6761a27e3961)

In the first place, can you use Akkoma from megalodon?

2023-06-04 00:03 UTC, h3poteto requested changes

2023-06-04 00:03 UTC, h3poteto commented on megalodon/src/misskey/api_client.ts
> +        quote: null
Misskey supports quote, so it should not be null.

2023-07-15 06:27 UTC, jorundev commented
Hello, how is it going? Does the maintainer of this PR only need to apply the change request for it to be mergeable?

2024-06-04 02:12 UTC, closed without merging